version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
    networks:
      - djangonetwork
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py crontab add && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
networks:
      djangonetwork:
          driver: bridge