# Generated by Django 4.0 on 2021-12-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_rename_article_comment_post_alter_post_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
